esphomeyaml:
  name: wemos_x
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: '<SSID>'
  password: '<PASSWORD>'

mqtt:
  broker: '<mqtt.example.com>'
  port: 1883
  # username: '<mqtt_user>'
  # password: '<mqtt_password>'
  # Start all MQTT published topics with the following prefix, make sure there is no trailing /
  topic_prefix: 'devices/wemos_x'


# Status LED, the built-in LED is on D4
status_led:
  pin: 
    number: D4 
    inverted: False

# Enable logging
logger:

ota:
  password: '<OTAPASSWORD>'

sensor:
  # Wifi is a builtin sensor
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 10s
  # The DHT11 is connected to D4
  # Every 5 seconds a new sample is taken
  - platform: dht
    pin: D4
    model: DHT11
    update_interval: 5s
    temperature:
      name: "Temperature"
      filters:
        - filter_nan:
        - sliding_window_moving_average:
            window_size: 1
            send_every: 1
        - unique:
    humidity:
      name: "Humidity"
      filters:
        - filter_nan:
        - sliding_window_moving_average:
            window_size: 1
            send_every: 1
        - unique:


